meta:
  engine: 4.1.0
  version: 1.1
  author: HagelzZ
  name: cicada
units:
  kx: cx
  ky: cy
  px: 3
  py: 3
  hx: cx/2
  hy: cy/2
points:
  zones:
    matrix:
      key:
        padding: ky+0.5
        spread: kx+0.5
      anchor:
        rotate: -10
        shift: [100, -150]
      columns:
        outer:
          key:
            col_net: P20
            mirror.col_net: P20
            height: ky
            width: kx
        pinky:
          key:
            col_net: P21
            mirror.col_net: P21
            height: ky
            width: kx
            stagger: 2.5
        ring:
          key:
            col_net: P3
            mirror.col_net: P3
            height: ky
            width: kx
            stagger: 7
        middle:
          key:
            col_net: P2
            mirror.col_net: P2
            height: ky
            width: kx
            stagger: 5
        index:
          key:
            col_net: P0
            mirror.col_net: P0
            height: ky
            width: kx
            stagger: -7
        indexfar:
          key:
            col_net: P1
            mirror.col_net: P1
            height: ky
            width: kx
            stagger: -2.5
      rows:
        bottom:
            row_net: P16
            mirror.row_net: P8
        home:
            row_net: P14
            mirror.row_net: P7
        top:
            row_net: P15
            mirror.row_net: P6
        number:
            row_net: P18
            mirror.row_net: P5
#        frow:
#            row_net: P19
#            mirror.row_net: P4
    thumbrow:
      key:
        padding: ky+0.5
        spread: kx+0.5
      anchor:
        ref: matrix_index_bottom
        shift: [0, -1.5ky]
      columns:
        near:
          key:
            col_net: P2
            mirror.col_net: P2
            splay: -21
            height: ky
            width: kx
        home:
          key:
            col_net: P0
            mirror.col_net: P0
            height: ky
            width: kx
        far:
          key:
            col_net: P1
            mirror.col_net: P1
            height: ky
            width: kx
      rows:
        thumb:
          row_net: P10
          mirror.row_net: P9
  mirror:
    ref: matrix_index_home
    distance: 90
outlines:
  keys:
    - what: rectangle
      where: true
      size: [kx, ky]
  board:
    - what: polygon
      operation: stack
      points:
        - ref: thumbrow_far_thumb
          shift: [hx+px, hy+py]
        - ref: thumbrow_far_thumb
          shift: [hx+px, -hy-py]
        - ref: thumbrow_near_thumb
          shift: [-hx-px, -hy-py]
        - ref: matrix_index_bottom
          shift: [-hx-px, -hy-py]
        - ref: matrix_ring_bottom
          shift: [hx+px, -hy-py]
        - ref: matrix_pinky_bottom
          shift: [hx+px, -hy-py]
        - ref: matrix_outer_bottom
          shift: [hx+px, -hy-py]
        - ref: matrix_outer_bottom
          shift: [-hx-px, -hy-py]
        - ref: matrix_outer_number
          shift: [-hx-px, hy+py]
        - ref: matrix_pinky_number
          shift: [-hx-px, hy+py]
        - ref: matrix_middle_number
          shift: [-hx-px, hy+py]
        - ref: matrix_middle_number
          shift: [hx+px, hy+py]
        - ref: matrix_indexfar_number
          shift: [hx+px, hy+py]
        - ref: matrix_indexfar_number
          shift: [hx+px, hy+py]
        - ref: mirror_matrix_indexfar_number
          shift: [hx+px, hy+py]
        - ref: mirror_matrix_indexfar_number
          shift: [hx+px, hy+py]
        - ref: mirror_matrix_middle_number
          shift: [hx+px, hy+py]
        - ref: mirror_matrix_middle_number
          shift: [-hx-px, hy+py]
        - ref: mirror_matrix_pinky_number
          shift: [-hx-px, hy+py]
        - ref: mirror_matrix_outer_number
          shift: [-hx-px, hy+py]
        - ref: mirror_matrix_outer_bottom
          shift: [-hx-px, -hy-py]
        - ref: mirror_matrix_outer_bottom
          shift: [hx+px, -hy-py]
        - ref: mirror_matrix_pinky_bottom
          shift: [hx+px, -hy-py]
        - ref: mirror_matrix_ring_bottom
          shift: [hx+px, -hy-py]
        - ref: mirror_matrix_index_bottom
          shift: [-hx-px, -hy-py]
        - ref: mirror_thumbrow_near_thumb
          shift: [-hx-px, -hy-py]
        - ref: mirror_thumbrow_far_thumb
          shift: [hx+px, -hy-py]
        - ref: mirror_thumbrow_far_thumb
          shift: [hx+px, hy+py]
      fillet: 3
  combo:
    - name: board
    - operation: subtract
      name: keys
pcbs:
  cicada:
    outlines:
      main:
        outline: board
    footprints:
      choc:
        where: true
        what: choc
        params:
          hotswap: false
          from: "{{col_net}}"
          to: "{{colrow}}"
      diode0:
        what: diode
        where:
          - /^matrix_.*/
          - /^thumbrow_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          rotate: 90
          shift: [8.5, -2]
      diode1:
        what: diode
        where:
          - /mirror.matrix_.*/
          - /mirror.thumbrow_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          rotate: -90
          shift: [8.5, -2]
      pro_micro:
        what: promicro
        params:
          orientation: down
        where:
          ref.aggregate.parts: [matrix_indexfar_number, mirror_matrix_indexfar_number]
          shift: [0, -11.5]
          rotate: -90
