meta:
  engine: 4.0.2
  version: 1
  author: HagelzZ
units:
  kx: cx
  ky: cy
  px: 3
  py: 3
  hx: cx/2
  hy: cy/2
points:
  zones:
    matrix:
      key:
        padding: cy+1
        spread: cx+1
      anchor:
        rotate: -10
        shift: [100, -150]
      columns:
        outer:
          key:
            height: cy
            width: cx
        pinky:
          key:
            height: cy
            width: cx
            stagger: 2.5
        ring:
          key:
            height: cy
            width: cx
            stagger: 7
        middle:
          key:
            height: cy
            width: cx
            stagger: 5
        index:
          key:
            height: cy
            width: cx
            stagger: -7
        indexfar:
          key:
            height: cy
            width: cx
            stagger: -2.5
      rows:
        bottom:
            row_net: P16
            mirror.row_net: P8
        home:
            row_net: P14
            mirror.row_net: P7
        top:
            row_net: P15
            mirror.row_net: P6
        number:
            row_net: P18
            mirror.row_net: P5
        frow:
            row_net: P19
            mirror.row_net: P4
    thumbrow:
      key:
        padding: cy+1
        spread: cx+1
      anchor:
        ref: matrix_index_bottom
        shift: [0, -1.5ky]
      columns:
        near:
          key:
            splay: -21
            height: cy
            width: cx
            #col_net: P
            #mirror.col_net: P
        home:
          key:
            height: cy
            width: cx
            #col_net: P20
            #mirror.col_net: P20
        far:
          key:
            height: cy
            width: cx
            #col_net: P21
            #mirror.col_net: P21
      rows:
        thumb:
          row_net: P10
          mirror.row_net: P9
  mirror:
    ref: matrix_index_home
    distance: 90
outlines:
  plate:
    - what: rectangle
      where: true
      size: [cx + px, cy + py]
      fillet: 3
    - what: polygon
      points:
        - ref: thumbrow_far_thumb
          shift: [hx+px, hy+py]
        - ref: thumbrow_far_thumb
          shift: [hx+px, -hy-py]
        - ref: thumbrow_near_thumb
          shift: [-hx-px, -hy-py]
        - ref: matrix_index_bottom
          shift: [-hx-px, -hy-py]
        - ref: matrix_ring_bottom
          shift: [hx+px, -hy-py]
        - ref: matrix_pinky_bottom
          shift: [hx+px, -hy-py]
        - ref: matrix_outer_bottom
          shift: [hx+px, -hy-py]
        - ref: matrix_outer_bottom
          shift: [-hx-px, -hy-py]
        - ref: matrix_outer_frow
          shift: [-hx-px, hy+py]
        - ref: matrix_pinky_frow
          shift: [-hx-px, hy+py]
        - ref: matrix_middle_frow
          shift: [-hx-px, hy+py]
        - ref: matrix_middle_frow
          shift: [hx+px, hy+py]
        - ref: matrix_indexfar_frow
          shift: [hx+px, hy+py]
        - ref: matrix_indexfar_number
          shift: [hx+px, hy+py]
        - ref: mirror_matrix_indexfar_number
          shift: [hx+px, hy+py]
        - ref: mirror_matrix_indexfar_frow
          shift: [hx+px, hy+py]
        - ref: mirror_matrix_middle_frow
          shift: [hx+px, hy+py]
        - ref: mirror_matrix_middle_frow
          shift: [-hx-px, hy+py]
        - ref: mirror_matrix_pinky_frow
          shift: [-hx-px, hy+py]
        - ref: mirror_matrix_outer_frow
          shift: [-hx-px, hy+py]
        - ref: mirror_matrix_outer_bottom
          shift: [-hx-px, -hy-py]
        - ref: mirror_matrix_outer_bottom
          shift: [hx+px, -hy-py]
        - ref: mirror_matrix_pinky_bottom
          shift: [hx+px, -hy-py]
        - ref: mirror_matrix_ring_bottom
          shift: [hx+px, -hy-py]
        - ref: mirror_matrix_index_bottom
          shift: [-hx-px, -hy-py]
        - ref: mirror_thumbrow_near_thumb
          shift: [-hx-px, -hy-py]
        - ref: mirror_thumbrow_far_thumb
          shift: [hx+px, -hy-py]
        - ref: mirror_thumbrow_far_thumb
          shift: [hx+px, hy+py]
      fillet: 3
      operation: add
pcbs:
  cicadav1:
    outlines:
      main:
        outline: plate
    footprints:
      hotswap_choc:
        where: true
        what: choc
        params:
          hotswap: true
          from: "{{col_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -8.5]
      pro_micro:
        what: promicro
        params:
          orientation: down
        where:
          ref.aggregate.parts: [matrix_indexfar_number, mirror_matrix_indexfar_number]
          shift: [0, -15]
          rotate: -90
