meta:
  engine: 4.0.2
  version: 1
  author: HagelzZ
units:
  kx: cx
  ky: cy
  px: 2
  py: 2
  hx: cx/2
  hy: cy/2
points:
  zones:
    matrix:
      anchor:
        rotate: -10
        shift: [100, -150]
      columns:
        outer:
        pinky:
          key.stagger: 2.5
        ring:
          key.stagger: 7
        middle:
          key.stagger: 5
        index:
          key:
            col_net: P20
            mirror.col_net: P0
          key.stagger: -7
        indexfar:
          key:
            col_net: P21
            mirror.col_net: P1
          key.stagger: -2.5
      rows:
        bottom:
        home:
        top:
        number:
        frow:
    thumbrow:
      anchor:
        ref: matrix_index_bottom
        shift: [0, -1.5ky]
      columns:
        near:
          key.splay: -21
          key.height: cy
          key.width: cx
        home:
          key.origin: [-11.75, -9]
          key.height: cy
          key.width: cx
        far:
          key.origin: [-9.5, -9]
          key.height: cy
          key.width: cx
      rows:
        thumb:
  mirror:
    ref: matrix_index_home
    distance: 90
outlines:
  plate:
    - what: rectangle
      where: true
      size: [cx + px, cy + py]
      fillet: 0
    - what: polygon
      points:
        - ref: thumbrow_far_thumb
          shift: [hx+3, hy+3]
        - ref: thumbrow_far_thumb
          shift: [hx+3, -hy-3]
        - ref: thumbrow_near_thumb
          shift: [-hx-3, -hy-3]
        - ref: matrix_index_bottom
          shift: [-hx-3, -hy-3]
        - ref: matrix_ring_bottom
          shift: [hx+3, -hy-3]
        - ref: matrix_pinky_bottom
          shift: [hx+3, -hy-3]
        - ref: matrix_outer_bottom
          shift: [hx+3, -hy-3]
        - ref: matrix_outer_bottom
          shift: [-hx-3, -hy-3]
        - ref: matrix_outer_frow
          shift: [-hx-3, hy+3]
        - ref: matrix_pinky_frow
          shift: [-hx-3, hy+3]
        - ref: matrix_middle_frow
          shift: [-hx-3, hy+3]
        - ref: matrix_middle_frow
          shift: [hx+3, hy+3]
        - ref: matrix_indexfar_frow
          shift: [hx+3, hy+3]
        - ref: matrix_indexfar_number
          shift: [hx+3, hy+3]
        - ref: mirror_matrix_indexfar_number
          shift: [hx+3, hy+3]
        - ref: mirror_matrix_indexfar_frow
          shift: [hx+3, hy+3]
        - ref: mirror_matrix_middle_frow
          shift: [hx+3, hy+3]
        - ref: mirror_matrix_middle_frow
          shift: [-hx-3, hy+3]
        - ref: mirror_matrix_pinky_frow
          shift: [-hx-3, hy+3]
        - ref: mirror_matrix_outer_frow
          shift: [-hx-3, hy+3]
        - ref: mirror_matrix_outer_bottom
          shift: [-hx-3, -hy-3]
        - ref: mirror_matrix_outer_bottom
          shift: [hx+3, -hy-3]
        - ref: mirror_matrix_pinky_bottom
          shift: [hx+3, -hy-3]
        - ref: mirror_matrix_ring_bottom
          shift: [hx+3, -hy-3]
        - ref: mirror_matrix_index_bottom
          shift: [-hx-3, -hy-3]
        - ref: mirror_thumbrow_near_thumb
          shift: [-hx-3, -hy-3]
        - ref: mirror_thumbrow_far_thumb
          shift: [hx+3, -hy-3]
        - ref: mirror_thumbrow_far_thumb
          shift: [hx+3, hy+3]
      fillet: 3
      operation: add
pcbs:
  cicadav1:
    outlines:
      main:
        outline: plate
    footprints:
      hotswap_choc:
        where: true
        what: choc
        params:
          hotswap: true
          from: "{{col_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -8.5]
      pro_micro:
        what: promicro
        params:
          orientation: down
        where:
          ref.aggregate.parts: [matrix_indexfar_number, mirror_matrix_indexfar_number]
          shift: [0, -15]
          rotate: -90
